package com.flightontrack.shared;

public interface Events {
    enum EVENT {
        MACT_BIGBUTTON_ONCLICK_START,
        MACT_BIGBUTTON_ONCLICK_STOP,
        MACT_BACKBUTTON_ONCLICK,
        MACT_MULTILEG_ONCLICK,

        FLIGHT_GETNEWFLIGHT_STARTED,
        FLIGHT_GETNEWFLIGHT_COMPLETED,
        FLIGHT_FLIGHTTIME_STARTED,
        FLIGHT_FLIGHTTIME_UPDATE_COMPLETED,
        FLIGHT_CLOSEFLIGHT_COMPLETED,
        FLIGHT_ONSPEEDABOVEMIN,
        FLIGHT_ONSPEEDLOW,
        FLIGHT_ONPOINTSLIMITREACHED,
        FLIGHT_STATECHANGEDTO_READYTOSAVE,
        FLIGHT_REMOTENUMBER_RECEIVED,
        FLIGHTBASE_GETFLIGHTNUM,

        SESSION_ONSENDCACHECOMPLETED,
        SESSION_ONSUCCESS_COMMAND,
        SESSION_ONSUCCESS_EXCEPTION,

        CLOCK_SERVICESTARTED_MODELOCATION,
        CLOCK_SERVICESELFSTOPPED,
        CLOCK_ONTICK,
        CLOCK_MODECLOCK_ONLY,

        PROP_CHANGED_MULTILEG,
        ROUTE_ONNEW,
        ROUTE_ONLEGLIMITREACHED,
        ROUTE_NOACTIVEROUTE,
        ROUTE_ONRESTART,

        SETTINGACT_BUTTONCLEARCACHE_CLICKED,

        SETTINGACT_BUTTONSENDCACHE_CLICKED,
        ALERT_SENTPOINTS,

        ALERT_STOPAPP,
        SQL_LOCALFLIGHTNUM_ALLOCATED,
        SQL_ONCLEARCACHE_COMPLETED,
        SQL_FLIGHTRECORDCOUNT_ZERO
    }
}
